import feedsJson from "@/data/feeds.json";
import protocolsJson from "@/data/protocols.json";
import coverageJson from "@/data/coverage.json";
import detailsJson from "@/data/details.json";
import syncedDefiscan from "@/data/synced/defiscan.json";
import excludedFeedsJson from "@/data/excluded-feeds.json";

export type CoverageStatus = "covered" | "partial" | "not-yet-covered";

export interface Feed {
  id: string;
  name: string;
  focus: string;
  type: "Rating" | "Dashboard" | "Monitoring" | "Research";
  url: string;
  accessibility: {
    // #66 categorization — orthogonal attributes, each MECE; "unknown" = not yet verified (SAT-302)
    api: "open" | "permissioned" | "paid" | "none" | "unknown";
    apiDocumented: "yes" | "no" | "unknown";
    // Public link to the API docs, when one exists (makes the ✓ clickable).
    apiDocsUrl?: string;
    // Independent of `api`: a feed can have both a free public tier and a paid
    // tier. When set, these override the values derived from `api`.
    apiFreePublic?: "yes" | "no" | "unknown";
    apiPaidTier?: "yes" | "no" | "unknown";
    publicDashboard: "yes" | "no" | "unknown";
    // Public link to the dashboard, when one exists (makes the ✓ clickable).
    dashboardUrl?: string;
    methodologyOpen: "yes" | "no" | "unknown";
    // Public link to the open methodology, when one exists (makes the ✓ clickable).
    methodologyUrl?: string;
    verified: boolean;
    note: string;
  };
  coverageBlocker: {
    kind: "provider-scope" | "access-gated" | "verification-pending";
    note: string;
  };
  // What the feed assesses, so the matrix can score protocol vs. vault coverage
  // independently (e.g. CuratorWatch: protocol no, vault yes). Absent ≡ "unknown".
  scope?: {
    protocolCoverage: "yes" | "no" | "unknown";
    vaultMonitoring: "yes" | "no" | "unknown";
  };
  // Whether the feed's data is actively reachable BY THIS AGGREGATOR (distinct
  // from what the provider offers publicly): "live" = we sync it, "available" =
  // usable API + validated path but no auto-sync yet, "none" = no access,
  // "unknown" = not yet assessed. Absent ≡ "unknown".
  aggregatorStatus?: "live" | "available" | "none" | "unknown";
}

export interface Protocol {
  id: string;
  name: string;
  family: string;
  versions?: string[];
  category: string;
  notes: string;
  metric: { kind: "tvl" | "volume24h"; slug: string | null };
}

export interface CoverageCell {
  status: CoverageStatus;
  provenance: string;
  note?: string;
  verbatim?: string;
  sourceUrl?: string;
  updated?: string | null;
}

export interface GovernanceFact {
  label: string;
  value: string;
  provenance: string;
  source: string;
}

export interface Audit {
  firm: string;
  scope: string;
  date: string;
  link: string;
}

export interface Incident {
  date: string;
  description: string;
  link: string;
}

export interface ProtocolDetail {
  governance: GovernanceFact[];
  audits: Audit[];
  incidents: Incident[];
}

export interface ExcludedFeed {
  id: string;
  name: string;
  reason: string;
  checked: string;
}

export const feeds = feedsJson.feeds as Feed[];
export const excludedFeeds = excludedFeedsJson.excluded as ExcludedFeed[];
export const protocols = protocolsJson.protocols as Protocol[];
export const details = detailsJson.details as unknown as Record<
  string,
  ProtocolDetail
>;

interface CoverageEntry {
  protocol: string;
  feed: string;
  status: string;
  provenance: string;
  note?: string;
  sourceUrl?: string;
}

const cellMap = new Map<string, CoverageCell>();
for (const e of coverageJson.entries as CoverageEntry[]) {
  cellMap.set(`${e.protocol}:${e.feed}`, {
    status: e.status as CoverageStatus,
    provenance: e.provenance,
    note: e.note,
    sourceUrl: e.sourceUrl,
  });
}

// Synced provider data (generated by scripts/sync-*.mjs) overrides manual
// curation: provider-published beats manual-unverified by definition.
interface SyncedEntry extends CoverageEntry {
  verbatim: string;
  sourceUrl: string;
  updated: string | null;
}
for (const e of syncedDefiscan.entries as SyncedEntry[]) {
  cellMap.set(`${e.protocol}:${e.feed}`, {
    status: e.status as CoverageStatus,
    provenance: e.provenance,
    note: e.note,
    verbatim: e.verbatim,
    sourceUrl: e.sourceUrl,
    updated: e.updated,
  });
}

// Every protocol×feed pair resolves to a labeled cell — unlisted pairs are
// explicitly "not yet covered / assessment pending", never blank (RFP hard req).
export function getCell(protocolId: string, feedId: string): CoverageCell {
  return (
    cellMap.get(`${protocolId}:${feedId}`) ?? {
      status: "not-yet-covered",
      provenance: "assessment-pending",
    }
  );
}

export function getProtocol(id: string): Protocol | undefined {
  return protocols.find((p) => p.id === id);
}

// Honest counting (peer-review finding: never let manual claims inflate
// "assessed"): provider-verified = synced verbatim data; claimed = manual
// curation pending first-hand verification.
export const providerVerifiedCellCount = [...cellMap.values()].filter(
  (c) => c.provenance === "provider-published"
).length;
export const claimedCellCount = cellMap.size - providerVerifiedCellCount;

// DefiLlama icon CDN slugs that differ from the metric slug.
const ICON_SLUG_OVERRIDES: Record<string, string> = {
  "cow-swap": "cowswap",
  "morpho-vaults": "morpho",
};

export function iconSlugFor(p: Protocol): string | null {
  return ICON_SLUG_OVERRIDES[p.id] ?? p.metric.slug;
}

const TYPE_ORDER = ["Rating", "Dashboard", "Monitoring", "Research"];

// Feeds grouped by methodology type for column ordering; registry order
// preserved within each type.
export const orderedFeeds: Feed[] = [...feeds].sort(
  (a, b) => TYPE_ORDER.indexOf(a.type) - TYPE_ORDER.indexOf(b.type)
);
