// Captures current DefiLlama metrics into data/metrics-snapshot.json so the
// site can fall back to a last-known value (with a visible stale badge) when
// a live fetch fails at ISR time. Run: node scripts/snapshot-metrics.mjs
// Refreshed by the nightly sync workflow.

import { readFile, writeFile } from "node:fs/promises";

const protocolsJson = JSON.parse(
  await readFile(new URL("../data/protocols.json", import.meta.url), "utf8")
);

async function fetchLive(metric) {
  if (!metric.slug) return null;
  try {
    if (metric.kind === "tvl") {
      const res = await fetch(`https://api.llama.fi/tvl/${metric.slug}`);
      if (!res.ok) return null;
      const n = await res.json();
      return typeof n === "number" ? n : null;
    }
    const res = await fetch(
      `https://api.llama.fi/summary/aggregators/${metric.slug}?dataType=dailyVolume`
    );
    if (!res.ok) return null;
    const d = await res.json();
    return typeof d.total24h === "number" ? d.total24h : null;
  } catch {
    return null;
  }
}

const values = {};
for (const p of protocolsJson.protocols) {
  const v = await fetchLive(p.metric);
  if (v !== null) values[p.metric.slug] = v;
}

await writeFile(
  new URL("../data/metrics-snapshot.json", import.meta.url),
  JSON.stringify(
    {
      $comment:
        "Generated by scripts/snapshot-metrics.mjs — last-known metric values used as fallback (rendered with a stale badge) when live fetch fails. Do not edit by hand.",
      generatedAt: new Date().toISOString(),
      values,
    },
    null,
    2
  ) + "\n"
);
console.log(`snapshot captured for ${Object.keys(values).length} slugs`);
